version: '2'
services:
    medicalagenda-app:
        image: medicalagenda
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://medicalagenda-mysql:3306/medicalagenda?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    medicalagenda-mysql:
        extends:
            file: mysql.yml
            service: medicalagenda-mysql
